---
- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
